### PR TITLE
Add zh_Hant_TW community L10N project

### PR DESCRIPTION
**Pull request by moda-l10n**
Add zh_Hant_TW community translations.
This is the version translated by the MoDA-l10n projects, which involved 1 English to Traditional Chinese translator and 2 peer reviewers who corrected typos and ensured consistency.
Each translation was uploaded to Weblate after going through the aforementioned review process and then committed to this project. This project also has a dedicated project page. The files for this commit and PR were taken from this branch and added. 
[Original Project](https://github.com/moda-l10n/publiccodenet.standard/tree/moda-i18n)

All Files on the list to translate base on 0.7.1
- [x]  index.md
- [x] all files in the folder criteria except for _template.md and index.md
    - [X] bundle-policy-and-code.md
    - [x] code-in-the-open.md
    - [x] continuous-integration.md
    - [x] document-maturity.md
    - [x] document-objectives.md
    - [x] documenting.md
    - [x] make-contributing-easy.md
    - [x] open-licenses.md
    - [x] open-standards.md
    - [x] open-to-contributions.md
    - [x] require-review.md
    - [x] reusable-and-portable-codebases.md
    - [x] understandable-english-first.md
    - [x] version-control-and-history.md
- [x] readers-guide.md
- [x] glossary.md
- [x] CONTRIBUTING.md
- [x] GOVERNANCE.md
- [x] CHANGELOG.md
- [x] AUTHORS.md
- [x] standard-print.html

### CODE REVIEW

**Comment by ericherman** [comment]
Who is qualified to review the hard work done here?

Even if you are not a professional translator, if you are fluent enough in both languages to either point out errors or confirm that it is a good translation, please do so.

**Comment by Ainali** [comment]
Totally separate and not a blocker for this pull request, but I make a note here, just in lack of a better place. It would be very interesting to hear about the experience of using Weblate as a translation tool (which was used if I recall correctly), and how the workflow for transforming the text was (and if it would be easy to replicate or reuse for other languages).

**Comment by ericherman** [comment]
I suggest that these reviews are sufficient for maintainers to choose to merge a courtesy translation.

Naturally, future readers/reviewers may wish to create issues to improve it, and those can be addressed at that time.

**Comment by clausmullie** [comment]
Wonderful, big thank you to everyone involved for the great work! :heart:

**Pull request merged**
